# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

crash <- function() {
    .Call(`_Apollonius_crash`)
}

test <- function(sites, radii) {
    .Call(`_Apollonius_test`, sites, radii)
}

test2 <- function(sites, radii) {
    .Call(`_Apollonius_test2`, sites, radii)
}

ApolloniusCpp <- function(sites, radii) {
    .Call(`_Apollonius_ApolloniusCpp`, sites, radii)
}

